# Use the official Python 3.8 image as a base image
FROM python:3.8

# Set the working directory to /app
WORKDIR /app

# Copy the Python publisher file to the container's working directory
COPY publisher/stream-producer.py /app/
COPY publisher/run_producer.sh /app/
RUN chmod +x /app/run_producer.sh
# Install the Paho MQTT library
RUN pip install paho-mqtt
RUN pip install faker

# Define the command to run the Python program
# CMD ["python", "mqtt_publisher.py"]
CMD ["/app/run_producer.sh"]